#!/bin/bash

cd ../fai

meteor build ../ec2  --architecture os.linux.x86_64

cd ../ec2

scp fai.tar.gz fai:/home/ubuntu

rm fai.tar.gz

ssh fai '
sudo chown -R ubuntu:ubuntu ~/.pm2
pm2 delete all
sudo rm -r bundle
tar zxf *.tar.gz
rm *.tar.gz
cd bundle
(cd programs/server && npm install)

cat <<EOT | tee -a app.json
{
  "apps" : [{
    "name"        : "fai",
    "script"      : "~/bundle/main.js",
    "env": {
      "MONGO_URL": "mongodb://localhost:27017/fai",
      "ROOT_URL": "http://54.237.241.243",
      "PORT": "80"
    }
  }]
}
EOT

pm2 start app.json --node-args="--max-old-space-size=256 --gc_interval=100"
pm2 save
'
