#!/bin/bash

cd ../simuc

meteor build ../ec2  --architecture os.linux.x86_64

cd ../ec2

scp simuc.tar.gz simuc:/home/ubuntu

rm simuc.tar.gz

ssh simuc '
sudo chown -R ubuntu:ubuntu ~/.pm2
pm2 delete all
sudo rm -r bundle
tar zxf *.tar.gz
rm *.tar.gz
cd bundle
(cd programs/server && npm install)

cat <<EOT | tee -a app.json
{
  "apps" : [{
    "name"        : "simuc",
    "script"      : "~/bundle/main.js",
    "env": {
      "MONGO_URL": "mongodb://localhost:27017/simuc",
      "ROOT_URL": "http://salasimuc.cl",
      "PORT": "80"
    }
  }]
}
EOT

pm2 start app.json --node-args="--max-old-space-size=256 --gc_interval=100"
pm2 save
'
