#!/bin/bash

sudo chown -R ubuntu:ubuntu ~/.pm2
pm2 delete all
sudo rm -r bundle
tar zxf *.tar.gz
rm *.tar.gz
cd bundle
(cd programs/server && npm install)

cat <<EOT | tee -a app.json
{
  "apps" : [{
    "name"        : "simuc2",
    "script"      : "main.js",
    "env": {
      "MONGO_URL": "mongodb://localhost:27017/simuc2",
      "ROOT_URL": "http://salasimuc.cl",
      "PORT": "3000"
    }
  }]
}
EOT

pm2 start app.json
pm2 save
